/**
 * Tesla Model S API 
 * A demo API to access and control the Tesla Model S
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TeslaModelSApi_);
  }
}(this, function(expect, TeslaModelSApi_) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TeslaModelSApi_.InlineResponse2003();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2003', function() {
    it('should create an instance of InlineResponse2003', function() {
      // uncomment below and update the code to test InlineResponse2003
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be.a(TeslaModelSApi_.InlineResponse2003);
    });

    it('should have the property insideTemp (base name: "inside_temp")', function() {
      // uncomment below and update the code to test the property insideTemp
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property outsideTemp (base name: "outside_temp")', function() {
      // uncomment below and update the code to test the property outsideTemp
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property driverTempSetting (base name: "driver_temp_setting")', function() {
      // uncomment below and update the code to test the property driverTempSetting
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property passengerTempSetting (base name: "passenger_temp_setting")', function() {
      // uncomment below and update the code to test the property passengerTempSetting
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property isAutoConditioningOn (base name: "is_auto_conditioning_on")', function() {
      // uncomment below and update the code to test the property isAutoConditioningOn
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property isFrontDefrosterOn (base name: "is_front_defroster_on")', function() {
      // uncomment below and update the code to test the property isFrontDefrosterOn
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property isRearDefrosterOn (base name: "is_rear_defroster_on")', function() {
      // uncomment below and update the code to test the property isRearDefrosterOn
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

    it('should have the property fanStatus (base name: "fan_status")', function() {
      // uncomment below and update the code to test the property fanStatus
      //var instane = new TeslaModelSApi_.InlineResponse2003();
      //expect(instance).to.be();
    });

  });

}));
