/**
 * Tesla Model S API 
 * A demo API to access and control the Tesla Model S
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TeslaModelSApi_);
  }
}(this, function(expect, TeslaModelSApi_) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TeslaModelSApi_.InlineResponse2001();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001', function() {
    it('should create an instance of InlineResponse2001', function() {
      // uncomment below and update the code to test InlineResponse2001
      //var instane = new TeslaModelSApi_.InlineResponse2001();
      //expect(instance).to.be.a(TeslaModelSApi_.InlineResponse2001);
    });

    it('should have the property shiftState (base name: "shift_state")', function() {
      // uncomment below and update the code to test the property shiftState
      //var instane = new TeslaModelSApi_.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property speed (base name: "speed")', function() {
      // uncomment below and update the code to test the property speed
      //var instane = new TeslaModelSApi_.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new TeslaModelSApi_.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new TeslaModelSApi_.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property heading (base name: "heading")', function() {
      // uncomment below and update the code to test the property heading
      //var instane = new TeslaModelSApi_.InlineResponse2001();
      //expect(instance).to.be();
    });

  });

}));
